project_id = "icvrrpxtycwgaxcajwdf"

[functions.extract-automation]
verify_jwt = false

[functions.hubspot-sync]
verify_jwt = true

[functions.zapier-sync]
verify_jwt = true

[functions.typeform-sync]
verify_jwt = true
