project_id = "icvrrpxtycwgaxcajwdf"

[functions.extract-automation]
verify_jwt = false

[functions.brandy-ask]
verify_jwt = false

[functions.brandy-feedback]
verify_jwt = false

[functions.hubspot-sync]
verify_jwt = true

[functions.zapier-sync]
verify_jwt = true

[functions.typeform-sync]
verify_jwt = true

[functions.gitlab-sync]
verify_jwt = true

[functions.brandy-analyse]
verify_jwt = false

[functions.enrich-automation]
verify_jwt = false

[functions.hubspot-pipelines]
verify_jwt = true
